Ariel
francobosio/Proyecto-Baku pull request #4
Opened 2021-08-07 21:39 UTC by zArielz

Pantallas Inicio, Home sin rutas

2021-08-07 21:59 UTC, fmarc002 commented on Producto/Código Fuente/Baku/baku/package.json
> +    "@material-ui/core": "^4.12.1",
mantener centrado con el resto. Justificar!

2021-08-07 21:59 UTC, fmarc002 commented on Producto/Código Fuente/Baku/baku/src/AppBar/AppBar.js
> +
borrar esta linea vacía

2021-08-07 21:59 UTC, fmarc002 commented on Producto/Código Fuente/Baku/baku/src/AppBar/AppBar.js
> +
borrar esta linea vacía

2021-08-07 22:00 UTC, fmarc002 commented on Producto/Código Fuente/Baku/baku/src/AppBar/AppBar.js
> +
borrar esta linea vacía

2021-08-07 22:00 UTC, fmarc002 commented on Producto/Código Fuente/Baku/baku/src/AppBar/AppBar.js
> +
borrar esta linea vacía

2021-08-07 22:01 UTC, fmarc002 commented on Producto/Código Fuente/Baku/baku/src/AppBar/AppBar.js
> +}
falta el ; ?

2021-08-07 22:01 UTC, fmarc002 commented on Producto/Código Fuente/Baku/baku/src/CarouselPrincipal/Content.js
> +export default Content;
agregar un linea vacía debajo de esto.

2021-08-07 22:01 UTC, fmarc002 commented on Producto/Código Fuente/Baku/baku/src/CarouselPrincipal/Content.scss
> +}
falta una linea vacía debajo de esto.

2021-08-07 22:02 UTC, fmarc002 commented on Producto/Código Fuente/Baku/baku/src/CarouselPrincipal/Item.js
> +export default Item;
agregar una linea vacía debajo de esto.

2021-08-07 22:02 UTC, fmarc002 commented on Producto/Código Fuente/Baku/baku/src/CarouselPrincipal/Mark.scss
> +
borrar linea vacía.

2021-08-07 22:02 UTC, fmarc002 commented on Producto/Código Fuente/Baku/baku/src/CarouselPrincipal/SlideButton.js
> +export default SlideButton;
agregar una linea vacía debajo de esto.

2021-08-07 22:03 UTC, fmarc002 commented on Producto/Código Fuente/Baku/baku/src/CarouselPrincipal/SlideButton.scss
> +
hay que borrar una linea vacía?

2021-08-07 22:03 UTC, fmarc002 commented on Producto/Código Fuente/Baku/baku/src/CarouselPrincipal/Slider.scss
> +
borrar linea vacía.

2021-08-07 22:04 UTC, fmarc002 commented on Producto/Código Fuente/Baku/baku/src/CarouselPrincipal/useSliding.js
> +const useSliding = (elementWidth, countElements) => {
justificar con el resto.

2021-08-07 22:04 UTC, fmarc002 commented on Producto/Código Fuente/Baku/baku/src/Footy/Footy.jsx
> +export default Footy
agregar una linea vacía debajo de esto.

2021-08-07 22:05 UTC, fmarc002 commented on Producto/Código Fuente/Baku/baku/src/Inicio/Inicio.js
> +
borrar linea vacía

2021-08-07 22:05 UTC, fmarc002 commented on Producto/Código Fuente/Baku/baku/src/Inicio/Inicio.js
> +}
agregar una linea vacía debajo de esto.

2021-08-07 22:06 UTC, fmarc002 commented on Producto/Código Fuente/Baku/baku/src/Login/Login.jsx
> +
borrar linea vacía

2021-08-07 22:06 UTC, fmarc002 commented on Producto/Código Fuente/Baku/baku/src/Login/Login.jsx
> +export default Login
agregar una linea vacía debajo de esto.

2021-08-07 22:07 UTC, fmarc002 requested changes
Corregir estos errores y poner capturas de las pantallas en el PR!

2021-08-09 00:27 UTC, francobosio requested changes

2021-08-09 00:27 UTC, francobosio commented on Producto/Código Fuente/Baku/baku/package.json
> +    "@material-ui/core": "^4.12.1",
indentar con el resto del codigo

2021-08-09 00:27 UTC, francobosio commented on Producto/Código Fuente/Baku/baku/src/AppBar/AppBar.js
> +
hay 2 lineas en blanco juntas, borrar una

2021-08-09 00:27 UTC, francobosio commented on Producto/Código Fuente/Baku/baku/src/AppBar/AppBar.js
> +
borrar linea en blanco

2021-08-09 00:27 UTC, francobosio commented on Producto/Código Fuente/Baku/baku/src/AppBar/AppBar.js
> +
borrar estas 2 lineas en blanco

2021-08-09 00:27 UTC, francobosio commented on Producto/Código Fuente/Baku/baku/src/AppBar/AppBar.js
> +}
finalizar cada sentencia con ;

2021-08-09 00:27 UTC, francobosio commented on Producto/Código Fuente/Baku/baku/src/CarouselPrincipal/Content.js
> +
borrar linea en blanco

2021-08-09 00:27 UTC, francobosio commented on Producto/Código Fuente/Baku/baku/src/CarouselPrincipal/Item.js
> +
borrar linea en blanco

2021-08-09 00:27 UTC, francobosio commented on Producto/Código Fuente/Baku/baku/src/CarouselPrincipal/Mark.scss
> +
borrar las 2 lineas en blanco

2021-08-09 00:27 UTC, francobosio commented on Producto/Código Fuente/Baku/baku/src/Footy/Footy.jsx
> +  //no se usa
si no se usa para que lo dejamos?

2021-08-09 00:27 UTC, francobosio commented on Producto/Código Fuente/Baku/baku/src/Inicio/Inicio.js
> +
borrar linea en blanco

2021-08-09 02:35 UTC, fmarc002 commented
![image](https://user-images.githubusercontent.com/73716133/128655089-559b817b-3ea2-430c-890a-f63e3892213d.png)
agregar una imagen más

2021-08-09 02:36 UTC, fmarc002 commented
Poner los  títulos correctos:
![image](https://user-images.githubusercontent.com/73716133/128655134-68d47133-3c97-4d11-9a31-6ffc56235842.png)

2021-08-09 02:36 UTC, fmarc002 commented
Se puede adaptar a formato responsive? 
![image](https://user-images.githubusercontent.com/73716133/128655162-52a3b6bb-8b2f-498c-b905-bfa03c55ee23.png)

2021-08-22 20:03 UTC, francobosio approved these changes

2021-08-22 21:31 UTC, fmarc002 approved these changes

2021-08-22 23:43 UTC, merged